[build]
  command = "npm run build"
  publish = ".next" # Adjust this to match your build output settings.
  functions = "netlify/functions" # Points to your functions directory.

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  functions = "netlify/functions"
